version: "3.9"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5456:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: nest
    networks:
      - nest_network
  test-db:
    image: postgres:13
    ports:
      - 5457:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: nest
    networks:
      - nest_network
networks:
  nest_network:
